### ISSUE TITLE
用您的模板生成的X64固件无法修改IP，改了重启还是最开始的IP。

### ISSUE THREAD

**Issue by jarod360** [bin20088/Bin#1]
用您的模板生成的X64固件无法修改IP，改了重启还是最开始的IP。不知道是哪里出错了，试了您自动生成的，正常改IP没问题。

**Comment by bin20088** [comment]
看看你的其他设置能不能保存吧，如果不能，那就是因为我添加的插件过多，固件超出默认大小，导致设置不能保存、无限重启等莫名其妙的问题。

**Comment by liker169** [comment]
可以试试给它读写权限后再使用，我就是这么搞定这个问题的
